version: "3.8"

services:
  item-app:
    image: ghcr.io/cecep31/a433-microservices:v1
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - item-db
    networks:
      - app-network

  item-db:
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-db:
